// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://peptpbfvieicauuiqawf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBlcHRwYmZ2aWVpY2F1dWlxYXdmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4ODYwODEsImV4cCI6MjA2NDQ2MjA4MX0.yIlbfWh-pyvnkqIfnl40GnTwnQIuRUOThriqF8wrg9I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);